version: '3'

services:
  db:
    image: postgres
    ports:
      - $POSTGRES_PORT:$NGINX_PORT
    volumes:
      - posgresdata:/var/lib/postgresql/data

    env_file:
      - ./.env
    restart: unless-stopped
    

  web:
    build:
      context: .
    env_file:
      - ./.env
    volumes:
      - static:/static
      - "/var/run/gunicorn.sock:/var/run/gunicorn.sock"
      - "/var/run/websocket.sock:/var/run/websocket.sock"
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - "/var/run/gunicorn.sock:/var/run/gunicorn.sock"
      - "/var/run/websocket.sock:/var/run/websocket.sock"
    ports:
      - $NGINX_PORT:$NGINX_PORT
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static:
  posgresdata:
 
